### PR TITLE
fix joblib import

### LINKED ISSUE #57: ImportError: cannot import name 'joblib' from 'sklearn.externals'
ImportError: cannot import name 'joblib' from 'sklearn.externals'

### PR DESCRIPTION
**Pull request by agramfort**
close #57

### CODE REVIEW

**Comment by jbschiratti** [comment]
@agramfort Hello :-) in your commit [9e6156a](https://github.com/mne-tools/mne-features/pull/58/commits/9e6156a62a7f8b2b5fb0ecf4cb0c26ba5d706071), the thing that beaks Travis is that the latest version of Numba (0.50.1) requires Scipy >=1.0 but 0.19 is installed (because of `conda install --yes --quiet numpy=1.11 matplotlib=1.5 scipy=0.19 scikit-learn pandas` in [.travis.yml](https://github.com/mne-tools/mne-features/blob/master/.travis.yml)). Removing `=0.19` and upgrading to the latest version of Scipy should fix Travis! Shall I make the change?

**Comment by agramfort** [comment]
Push on my PR you should be able to

Thanks

**Comment by agramfort** [comment]
FYI you can now install mne-features from pypi https://pypi.org/project/mne-features/

**Comment by jbschiratti** [comment]
Great, thanks! It'll be nice for users to have a release on pypi.
Now there's been a release, should we discuss next steps? (keep the repo living and, why not, future releases?)

**Comment by agramfort** [comment]
I pushed this to pypi as I see more users. But I have little time to push this forward

**Pull request merged**
