### PR TITLE
Add documentation page to setup.py

### PR DESCRIPTION
**Pull request by sappelhoff**
fix for https://github.com/mne-tools/mne-python/blob/071a98fae28bd7c32c6ce357076263ef01031994/doc/sphinxext/related_software.py#L78

- xref https://github.com/mne-tools/mne-python/pull/12731

cc @larsoner

### CODE REVIEW

**Comment by sappelhoff** [comment]
@hoechenberger you seem to have merge rights here, perhaps you could do me the honor and merge this very minor fix :-)

**Comment by hoechenberger** [comment]
Nope I cannot merge here, sorry! 😢

**Comment by sappelhoff** [comment]
oups, sorry, I have misinterpreted the commit history 😬

**Comment by larsoner** [comment]
Thanks @sappelhoff !

**Pull request merged**
