### PR TITLE
Github Actions

### PR DESCRIPTION
**Pull request by jbschiratti**
Moving from Travis CI to Github Actions.

### CODE REVIEW

**Comment by agramfort** [comment]
I don’t see the CIs running. Here. Can you make sure it’s running on pull request. Let’s wait for green CIs before merging

**Comment by jbschiratti** [comment]
@agramfort The CI is green on my fork (see the result [here](https://github.com/jbschiratti/mne-features/actions/runs/1409482788)). 

Strangely, Actions are not triggered on this repository _yet_ (probably because there's no `.github` folder on master).

**Comment by jasmainak** [comment]
You need to make a pull request from `mne-tools` not your fork the first time for github actions to work. I haven't found another way to make it work :)

**Comment by agramfort** [comment]
ok let's merge this and see how it goes on master...

**Comment by agramfort** [comment]
seems to work 

@jbschiratti can you send a PR to update the button in the readme? 🙏

**Pull request merged**
